### ISSUE TITLE
Refactor `UserName` to `Username`

### ISSUE THREAD

**Issue by a-t-0** [HiveMinds-EU/tw-install#26]
<p>In entire repo. (mainly java codes. In eclipse Ctrl+h, case sensitive.)</p>

**Comment by mohitsaxenaknoldus** [comment]
Please assign it to me, I will do it.

**Comment by mohitsaxenaknoldus** [comment]
Hey, I searched the whole project for `UserName` but it isn't present?

**Comment by a-t-0** [comment]
Excellent, then that was an old issue from when Java was used for the WSL. It's resolved, thank you for verifying!
