### ISSUE TITLE
Set up continuous integration testing

### ISSUE THREAD

**Issue by a-t-0** [HiveMinds-EU/tw-install#63]
- [ ] Write integration tests that verify whether the installation was successful.
- [ ] Then run these tests every time one pushes to master
- [ ] Allow calling the CI on a particular branch.
- [ ] Automatically trigger CI builds for pull requests.
- [ ] Write some actual meaningfull unit/integration tests (see separate issue).

**Comment by mohitsaxenaknoldus** [comment]
Please assign it to me, I'll do it.

**Comment by a-t-0** [comment]
Awesome, my Travis credits are through. I intend to host my own GitLab CI not upcoming week but the week after that.

Here is an example that has CI enabled:
https://github.com/a-t-0/shell_unit_testing_template

**Comment by mohitsaxenaknoldus** [comment]
I think 9 tasks are a lot for this one issue. Can we split this?

**Comment by a-t-0** [comment]
Yes, I removed the "host your own GitLab tasks", that is almost done over here:https://github.com/TruCol/setup_your_own_GitLab_CI  and I got another account for Travis CI credits.

So basically if you focus on the remaining 5 issues on actually setting up the CI configuration in this repo (which is what the title is about), then it would be wonderful!

**Comment by mohitsaxenaknoldus** [comment]
Sure! I've set up the project on Gitlab. I'll write a CI pipeline now.

**Comment by mohitsaxenaknoldus** [comment]
You want me to use `GitLab` right? @a-t-0 or `TravicCI`?

**Comment by a-t-0** [comment]
In the end I will host my own GitLab using that other repo I linked, but I did not yet figure out how to mirror this GitHub repository in the GitLab server. So if you can figure that out/can automate that, while you run it on GitLab your/some, it would be nice.

However, if you do not want to bother with GitLab, you can simply push the working CI configuration for travis, and I will fork it and run Travis CI from another account. So it is up to you, what you find fun :)

**Comment by mohitsaxenaknoldus** [comment]
> **In the end I will host my own GitLab using [that other repo](https://github.com/TruCol/setup_your_own_GitLab_CI) but that repo also still requires some work, and I did not yet figure out how to mirror this GitHub repository in the GitLab server. So if you can figure that out/can automate mirroring the this GitHub while you run it on your own/some GitLab, it would be a nice bonus.**

I've done this much. I'll push the pipeline file tomorrow so you can merge it with the master. I've tested it and it's working for all commits and PR's. Then, I'll help you mirror the repo with the GitLab server. Is it somehow possible to give me guest access to your GitLab server so I can do the setup? If not, I can give instructions here as well on how to mirror.

**Comment by a-t-0** [comment]
Awesome! Thanks, my GitLab server is not running yet, as I am still improving the installation procedure. When I run tests I remove the Server and install a new one, so a manual configuration of a mirror  would currently go lost. A brief script that mirrors this GitHub on an arbitrary GitLab server would be appreciated, otherwise I'll look into that later (I'm slightly time constraint so can't set that up upcomming 3 days). 

Nice work, I look forward to the pipeline creation:)

**Comment by mohitsaxenaknoldus** [comment]
> Awesome! Thanks, my GitLab server is not running yet, as I am still improving the installation procedure. So I cannot give you guest access right now. When I run tests I remove the Server and install a new one, so a manual configuration of a mirror  would currently go lost. A brief script that mirrors this GitHub on an arbitrary GitLab server would be appreciated, otherwise I'll look into that later (I'm slightly time constraint so can't set that up upcomming 3 days). 
> 
> Nice work, I look forward to the pipeline creation:)

Whats the need to remove and install a new server everytime? You can just integrate with GitLab with a free account and let it run the tests.

I have one more question, what does the `test` directory do? I saw it links to 3 different repos. Can you explain what those repos do and how your tests are running?

**Comment by mohitsaxenaknoldus** [comment]
Yes, thanks for the explanation. Great thoughts!

**Comment by mohitsaxenaknoldus** [comment]
@a-t-0 Can you add the `.bats` test files here so I can run those as tests?

**Comment by a-t-0** [comment]
I can not allocate time for that right now, if you want you can copy any arbitrary test/bats file, e.g. from https://github.com/TruCol/setup_your_own_GitLab_CI/blob/master/test/test_src_helper.bats or from productivityphone, and for example write an assert that checks whether the 

```

remove_logs() {
  rm -r src/logs/*
}
```
of file https://github.com/HiveMinds-EU/tw-install/blob/main/src/helper.sh actually removed the folder.
Otherwise I will do it next week.

**Comment by mohitsaxenaknoldus** [comment]
Ok i'll do that👍

**Comment by mohitsaxenaknoldus** [comment]
@a-t-0 When are these `src/logs/*` logs created?

**Comment by mohitsaxenaknoldus** [comment]
Also, PR: https://github.com/HiveMinds-EU/tw-install/pull/88
