### ISSUE TITLE
Clean up the installation code. 

### ISSUE THREAD

**Issue by a-t-0** [HiveMinds-EU/tw-install#68]
- [ ] Clean up the code, compliant with: https://google.github.io/styleguide/shellguide.html
- [ ] Make the code ShellCheck compliant

**Comment by mohitsaxenaknoldus** [comment]
Please assign it to me, I will do it.

**Comment by mohitsaxenaknoldus** [comment]
Do you want me to set base to this new branch you created?

**Comment by a-t-0** [comment]
Yes please. Also, I would not put too much effort into the `tw-install.sh` and `tw-uninstall.sh` files as they willl be replaced with this filestructure:
https://github.com/TruCol/setup_your_own_GitLab_CI/blob/master/install_gitlab.sh
and this one:
https://github.com/TruCol/setup_your_own_GitLab_CI/blob/master/uninstall_gitlab.sh
in order to resolve issue #81

**Comment by mohitsaxenaknoldus** [comment]
PR opened: https://github.com/HiveMinds-EU/tw-install/pull/85
