### ISSUE TITLE
Prevent requirement for reboot after uninstallation

### ISSUE THREAD

**Issue by a-t-0** [HiveMinds-EU/tw-install#69]
<p>Currently the software requires a reboot after installation before the software can be installed succesfully again.</p>
<p>It would be nice to be able to directly re-install after uninstalling (as a developer), without reboot. Perhaps this can be done by first stopping all taskwarrior and/or taskserver related services/processes before removing the files/uninstalling. In particular perhaps</p>
<div class="snippet-clipboard-content position-relative"><pre><code>taskdctl stop
</code></pre><div class="zeroclipboard-container position-absolute right-0 top-0">
    <clipboard-copy aria-label="Copy" class="ClipboardButton btn js-clipboard-copy m-2 p-0 tooltipped-no-delay" data-copy-feedback="Copied!" data-tooltip-direction="w" value="taskdctl stop
" tabindex="0" role="button">
      <svg aria-hidden="true" viewBox="0 0 16 16" version="1.1" data-view-component="true" height="16" width="16" class="octicon octicon-clippy js-clipboard-clippy-icon m-2">
    <path fill-rule="evenodd" d="M5.75 1a.75.75 0 00-.75.75v3c0 .414.336.75.75.75h4.5a.75.75 0 00.75-.75v-3a.75.75 0 00-.75-.75h-4.5zm.75 3V2.5h3V4h-3zm-2.874-.467a.75.75 0 00-.752-1.298A1.75 1.75 0 002 3.75v9.5c0 .966.784 1.75 1.75 1.75h8.5A1.75 1.75 0 0014 13.25v-9.5a1.75 1.75 0 00-.874-1.515.75.75 0 10-.752 1.298.25.25 0 01.126.217v9.5a.25.25 0 01-.25.25h-8.5a.25.25 0 01-.25-.25v-9.5a.25.25 0 01.126-.217z"></path>
</svg>
      <svg aria-hidden="true" viewBox="0 0 16 16" version="1.1" data-view-component="true" height="16" width="16" class="octicon octicon-check js-clipboard-check-icon color-text-success d-none m-2">
    <path fill-rule="evenodd" d="M13.78 4.22a.75.75 0 010 1.06l-7.25 7.25a.75.75 0 01-1.06 0L2.22 9.28a.75.75 0 011.06-1.06L6 10.94l6.72-6.72a.75.75 0 011.06 0z"></path>
</svg>
    </clipboard-copy>
  </div></div>
<p>at the start of the <code>uninstall.sh</code> would be sufficient to allow direct re-installation after uninstall without reboot. Otherwise investigate more, to enable the user to directly re-install the taskserver automatically without reboot.</p>

**Comment by mohitsaxenaknoldus** [comment]
Please assign it to me, I'll do it.

**Comment by mohitsaxenaknoldus** [comment]
@a-t-0 You are right, adding `taskdctl stop` at the top fixed the problem. I've tested.
PR raised: https://github.com/HiveMinds-EU/tw-install/pull/87

**Comment by a-t-0** [comment]
Marvellous! Thank you for testing it manually!
